# main workflow; ported from .travis.yaml
name: main

on:
  push:
    branches: [ '*', $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            python-version: ['3.10', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libopenmpi-dev openmpi-bin python3-numpy cython3 python3-mpi4py
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build pytest pytest-mpi
    - name: Build
      run: |
        python -m build
    - name: Install
      run:
        python -m pip install --user dist/mpsort*.whl
    - name: Python unit tests
      run: |
        python setup.py build_ext --inplace
        pytest
        mpirun -n 1 python -m pytest --with-mpi
        mpirun -n 2 python -m pytest --with-mpi
        mpirun -n 3 --oversubscribe python -m pytest --with-mpi
        mpirun -n 4 --oversubscribe python -m pytest --with-mpi
    - name: Version
      run: bash check_tag.sh mpsort/version.py
#    - export CFLAGS="${CFLAGS} -Wall"
#deploy:
#    - provider: pypi
#      distributions: sdist
#      user: "rainwoodman"
#      password:
#          secure: "cvta3oslqLseiE4bQxSk2CLeL6ZjdNyOQ660k7Y8vKXMWyjJikkG0MWEyHpDiYNXfAqcJZBnqruJ3+7XNOxQxahDSxXkiHruFASliUaEZPiLSvXZ9RrTCoz4epU6bwqHhENn2+JSyBbO4kzzp/4fttj+1bjTF4+4KDZ5UdagaccXke6cuf7T6VkuEGLqn5gfOteweQ/G0iwrqixd+w7HGjkwWSiGi3FTYjVY2B14sx0OiDx6vzLSo9IrRD7yh0DL7BWdcq+UpvnhcO2mtjYpIlgjULa7H3BqSQj2EhTQ0IaOfmK010n3bwL9NWjc6wZElEcbOLeIGx58tK0SknQiJgKvI59rnKLgVNjpSwT1V2wqD+CzHjRavR08OherMIjPg3PVJx8Q6nj3EeNJU9T6l6JFZFgFZBi+hve9NCh6gOQkIR7F2b7riIhu3oPIV+0I8EJ27hiegg1IYASyvxu1ubhuHb+Fsd5iKHE7vtxj0lkOOI6cs9fSPdnw7clPVytotvIdN+IRz/arotYf2t33zEPgEQ1j/J+ZC5mLLPsuPO7WUivABEVYxqAzZMpkakTxEtTDcvXwv8ij+lkWjQiU65Zwn/d1tBC62AxMBOW9BHAqBC7xct4CyUIHrTvv9Xt85/tvysVhBFZppEnfsfyIBM4gNhAEVy0RqAlkjpFXh0o="
#      on:
#        tags   : true
#        condition : $TRAVIS_PYTHON_VERSION = "3.7"
